name: Scheduler

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [main]

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i

      - name: Fetch notion supporters
        run: npm run update:notion
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}

      - name: Update sponsors.svg
        run: npx sponsors-cli -w 800 -s false && npx sponsors-cli -w 1300 -o sponsors.wide.svg -s false
        env:
          SPONSORS_TOKEN: ${{ secrets.SPONSORS_TOKEN }}
          SPONSORS_LOGIN: 2nthony

      - name: Commit
        uses: EndBug/add-and-commit@v4
        with:
          message: 'Chore: update sponsors.svg'
          add: 'sponsors.*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
